"""Write and read policies.

This module is where the three in-task memory "facets" actually differ. The
store treats ``type`` as a plain field; the *behavior* (what is worth writing,
how to dedup, how to retrieve and assemble) lives here.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Callable, Dict, List, Optional, Tuple

from . import embeddings, retrieval
from .schema import MemoryItem, MemoryType
from .store import MemoryStore

# The relation judge takes (new_item, candidate_item) and returns a verdict dict
# {"relation": duplicate|merge|supersede|conflict|distinct, "canonical": str?,
#  "winner": "new"|"existing"?, "reason": str?}. It is provided by the caller
# (an LLM); there is no deterministic fallback once a near-duplicate is found.
Judge = Callable[[MemoryItem, MemoryItem], Dict[str, Any]]

# What classify() decides a new write should do relative to an existing item.
ClassifyResult = Tuple[str, Optional[MemoryItem], Dict[str, Any]]


def _jaccard(a: List[str], b: List[str]) -> float:
    sa, sb = set(a), set(b)
    if not sa or not sb:
        return 0.0
    return len(sa & sb) / len(sa | sb)


@dataclass
class WritePolicy:
    """Decides whether/how an item enters the store.

    Exact duplicates are dropped cheaply (normalized content hash). For the
    semantic facet a near-duplicate *candidate* is generated by embedding cosine
    (lexical jaccard fallback), and the actual relation - same assertion
    (``merge``), contradiction where the new claim wins (``supersede``),
    contradiction left undecided (``conflict``), or unrelated (``new``) - is
    ALWAYS decided by the injected LLM ``judge``. There is no deterministic
    relation fallback: an LLM is mandatory once a candidate exists.
    """

    dedup_threshold: float = 0.85  # jaccard: exact-ish dup (non-semantic / no embeddings)
    candidate_sim: float = 0.6     # cosine: similar enough to be worth judging

    def should_store(self, item: MemoryItem) -> bool:
        # Selectivity: drop trivially short content. Episodic actions are always
        # kept (they are the audit log that powers dedup of *work*).
        if item.type == "episodic":
            return True
        return len(item.content.strip()) >= 8

    def classify(
        self, item: MemoryItem, store: MemoryStore, judge: Optional[Judge] = None
    ) -> ClassifyResult:
        """Decide how ``item`` enters the store.

        Returns ``(op, existing, verdict)`` where ``op`` is one of:
        ``new`` (store fresh, active), ``exact_dup`` (drop; identical to
        ``existing``), ``merge`` (same assertion as ``existing``), ``supersede``
        (contradicts ``existing``), or ``conflict`` (contradicts, undecided).
        ``verdict`` is the LLM judge's raw dict (empty for the no-LLM paths).
        """
        same_type = store.query(type=item.type)

        # 1) Exact duplicate (no LLM): normalized hash, or identical same-source text.
        for existing in same_type:
            if item.content_hash and existing.content_hash == item.content_hash:
                return ("exact_dup", existing, {})
            if item.source and existing.source == item.source and (
                existing.content.strip() == item.content.strip()
            ):
                return ("exact_dup", existing, {})

        # 2) Non-semantic facets keep the cheap jaccard dedup and never call an LLM.
        if item.type != "semantic":
            for existing in same_type:
                if _jaccard(item.keywords, existing.keywords) >= self.dedup_threshold:
                    return ("exact_dup", existing, {})
            return ("new", None, {})

        # 3) Semantic near-dup / contradiction: only consider live (active) claims.
        active = [e for e in same_type if e.status == "active"]
        candidate = self._best_candidate(item, active, store)
        if candidate is None:
            return ("new", None, {})

        # 4) The relation is ALWAYS the LLM's call - no deterministic fallback.
        if judge is None:
            raise RuntimeError(
                "WritePolicy.classify found a near-duplicate candidate but no LLM "
                "judge is configured. An LLM is required to decide merge/supersede/"
                "conflict; pass judge= into MemoryManager."
            )
        verdict = judge(item, candidate) or {}
        relation = str(verdict.get("relation", "")).strip().lower()
        if relation in ("duplicate", "merge"):
            return ("merge", candidate, verdict)
        if relation == "supersede":
            return ("supersede", candidate, verdict)
        if relation == "conflict":
            return ("conflict", candidate, verdict)
        return ("new", None, verdict)

    def _best_candidate(
        self, item: MemoryItem, candidates: List[MemoryItem], store: MemoryStore
    ) -> Optional[MemoryItem]:
        """Most-similar same-type candidate (embedding cosine, jaccard fallback)."""
        if not candidates:
            return None
        item_vec = embeddings.encode(item.content)
        vectors = store.semantic_vectors() if hasattr(store, "semantic_vectors") else {}
        if item_vec is not None and vectors:
            best, best_sim = None, 0.0
            for ex in candidates:
                ev = vectors.get(ex.id)
                if ev is None:
                    continue
                sim = retrieval._cosine(item_vec, ev)  # type: ignore[arg-type]
                if sim > best_sim:
                    best, best_sim = ex, sim
            return best if (best is not None and best_sim >= self.candidate_sim) else None
        # Lexical fallback when embeddings are unavailable.
        best, best_j = None, 0.0
        for ex in candidates:
            j = _jaccard(item.keywords, ex.keywords)
            if j > best_j:
                best, best_j = ex, j
        return best if (best is not None and best_j >= self.dedup_threshold) else None


@dataclass
class ReadPolicy:
    """Decides what gets recalled and how it is assembled into context."""

    top_k: int = 5
    min_score: float = 0.05

    def recall(
        self,
        query: str,
        store: MemoryStore,
        type: Optional[MemoryType] = None,
        task_id: Optional[str] = None,
        top_k: Optional[int] = None,
    ) -> List[MemoryItem]:
        candidates = store.query(type=type, task_id=task_id) if (
            type or task_id
        ) else store.all()
        # Consistency: recall only live claims. ``superseded`` / ``merged`` items
        # stay on disk for provenance but never reach recall or synthesis.
        candidates = [c for c in candidates if getattr(c, "status", "active") == "active"]
        # Semantic recall goes hybrid when embeddings are available: compute the
        # query vector once and hand the {id: vector} sidecar to the ranker.
        # Everything else (episodic/working) stays lexical.
        query_vec = None
        vectors = None
        if type == "semantic":
            query_vec = embeddings.encode(query)
            if query_vec is not None and hasattr(store, "semantic_vectors"):
                vectors = store.semantic_vectors()
        ranked = retrieval.rank(
            query,
            candidates,
            top_k=top_k or self.top_k,
            min_score=self.min_score,
            query_vec=query_vec,
            vectors=vectors,
        )
        return [item for item, _ in ranked]

    def assemble_context(self, items: List[MemoryItem], max_chars: int = 2000) -> str:
        """Turn recalled items into a compact, prompt-injectable block."""
        if not items:
            return "(no relevant memory)"
        lines: List[str] = []
        used = 0
        for it in items:
            src = f" [src: {it.source}]" if it.source else ""
            disputed = " [disputed: sources disagree]" if (it.links or {}).get("conflicts_with") else ""
            line = f"- ({it.type}) {it.content}{disputed}{src}"
            if used + len(line) > max_chars:
                break
            lines.append(line)
            used += len(line)
        return "\n".join(lines)
